CREATE DATABASE huiFeng;
USE huiFeng;

DROP TABLE IF EXISTS user;
CREATE TABLE user(
  id INT AUTO_INCREMENT PRIMARY KEY COMMENT 'id',
  loginName VARCHAR(40) NOT NULL UNIQUE COMMENT '登陆账号',
  name  VARCHAR(40) NOT NULL UNIQUE COMMENT '用户姓名',
  nickName  VARCHAR(40) NOT NULL UNIQUE COMMENT '用户昵称',
  password  VARCHAR(40) NOT NULL UNIQUE COMMENT '登陆密码',
  phone  VARCHAR(40) NOT NULL UNIQUE COMMENT '用户电话',
  IdCard  VARCHAR(40) NOT NULL UNIQUE COMMENT '用户身份证',
  birthday  DATE NOT NULL COMMENT '用户生日',
  sex  INT NOT NULL COMMENT '性别 0男，1女'
)COMMENT '用户表';
SELECT *
FROM user;